---
title: "Disorders of affect"
---

## Major Depressive Disorder (MDD)

### Symptoms

+ Unhappy mood, insomnia, lethargy, loss of pleasure, interest, energy
- Agitation
- Lasting for several weeks or more
- Experienced by ~7% Americans in any year
- Prevalence (up to ~20% lifetime)
- Females 2-3x males, higher 40+ years of age
    - postpartum anxiety and depression in 10-20% of mothers
- MZ concordance ~60% vs. DZ ~20% suggests genetic component

![[@mahar_stress_2014]](../include/img/mahar-table-1.jpg)

### Neurobiology

#### Reduced sizes of brain regions

- Reduced hippocampal volumes

Left Hippocampus

::: {layout-ncol-2}

![[@Videbech2004-sm]. Left hippocampus](../include/img/videbech-left-hipp.jpg)

![[@Videbech2004-sm]. Right hippocampus](../include/img/videbech-right-hipp.jpg)

:::

![[@Palazidou2012-je]](../include/img/palazido-2012-table-1.jpg)

#### Hypoactivity

+ Frontal and temporal cortex
+ Anterior cingulate
+ Insula
+ Cerebellum

![[@fitzgerald_meta-analytic_2008]. [a] patients v. ctrls, [b] patients on SSRIs, [c] patients v. ctrls (happy stim), [d] patients v. controls (sad stim)](../include/img/fitzgerald-2008.jpg)

#### Hyperactivity

![[@Hamilton2012-iv]](http://ajp.psychiatryonline.org/na101/home/literatum/publisher/app/journals/content/ajp/2012/ajp.2012.169.issue-7/appi.ajp.2012.11071105/production/images/large/ajp.169.7.693.f001.jpeg)

- Both valence-specific and non-valence specific

![[@Hamilton2012-iv]](http://ajp.psychiatryonline.org/na101/home/literatum/publisher/app/journals/content/ajp/2012/ajp.2012.169.issue-7/appi.ajp.2012.11071105/production/images/large/ajp.169.7.693.f002.jpeg)

[[@Hamilton2012-iv]](https://doi.org/10.1176/appi.ajp.2012.11071105)

### Altered connectivity

- Increased connectivity between resting state network regions and dorsal PFC [[@Sheline2010-nh]](http://doi.org/10.1073/pnas.1000446107)

![[@Sheline2010-nh]. Seed regions and targets. Each of the three solid circles corresponds to a seed region in the DLPFC, part of the CCN (yellow); precuneus, part of the DMN (pink); and subgenual and pregenual cingulate cortex, the affective division of the ACC (16) (turquoise). The correspondingly colored open circles represent regions with significantly increased connectivity with the respective seed regions. CCN (yellow); precuneus, part of DMN (pink); and affective division of the ACC (turquoise)](https://www.pnas.org/cms/10.1073/pnas.1000446107/asset/96a2e572-5688-4e55-ab30-9bd5843aa80a/assets/graphic/pnas.1000446107fig01.jpeg)

#### [@cheng_medial_2016]

- Resting state fMRI (rsFMRI) in 421 patients with major depressive disorder and 488 control subjects.
- Reduced connectivity between orbitofrontal cortex (OFC) and other areas of the brain
- Increased connectivity between lateral PFC and other brain areas

![[@cheng_medial_2016]](../include/img/cheng-2016-F1.large-1.jpg)

![[@cheng_medial_2016]](../include/img/cheng-2016-F2.large-1.jpg)

#### Summary

![[@Palazidou2012-je]](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bmb/101/1/10.1093/bmb/lds004/2/m_lds00401.jpeg?Expires=2147483647&Signature=k1Ppd9IqxUhmxtQcyGvxydDeNZSpuLGX9jgNGFy3URlPun5aK2dwxJbyGEGXrXDKdWhBxXxEpzU~mVWqz0B3YC1U4~W10tC0K8r91ynB2r-3lHarpCQnPDZBF2LIP302Mp3VL8MTh9YSQH5EtSmpRjeGOc2OPBC4XPHXdAZl~-5OVz4TtSJNBhXfHoSqabwtN9xHAJJAVkJ7kxpZp3vfVc8JK71NEcBauD7ZM40WtnsIfSIFHc~UvSECc-mbSIJAb1zmbom9U-80FG9NfEc0DbO-xJQTowuJqZD2fig~tlMFCATL8Wk8NwY4ushk~K99gQCJnYpq-~wQbtSacPBzOQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA)

<!-- Summary of brain areas implicated in depression -->

### Pharmacological factors

![[@Palazidou2012-je]](../include/img/palazido-2012-table-2.jpg)

<!-- Neurochemical and hormonal alterations in depression -->

- Endocrine
    + Thyroid dysfunction [@Medici2014-pn]
    + Altered cortisol reactivity [@Burke2005-ya]
- Brain-derived neurotrophic factor (BDNF)
- Proinflammatory cytokines

#### Monoamine (5-HT and NE) hypothesis

+ More: euphoria
+ Less: depression
- Evidence for
  + Resperine (antagonist for NE & 5-HT) can cause depression
  + Low serotonin (5-HT) metabolite levels in CSF of suicidal depressives [@samuelsson_csf_2006]
    
##### Measuring 5-HT

- CSF, platelets, plasma, urine, saliva
- CSF & platelets correlate highly [@Audhya2012-sv]
- But salivary 5-HT does not correlate with mood symptoms [@Leung2018-ks]

### Treatments

#### Psychotherapy: Neural responses

- increased rostral anterior cingulate cortex (rACC) activation vs. decrease in healthy controls
- decreased activity in left precentral gyrus

![[@Sankar2018-yp]. Fig. 2. Group by time interaction effects of psychological therapies. There was a significant group by time interaction in the left rostral anterior cingulate cortex, in which participants with major depression showed increased activity following psychological therapy while healthy participants showed a reduction in activity at the follow up scan. Sagittal (x), coronal (y), and axial (x) coordinates for each section are presented. Results are *P* < 0.05 FDR corrected.](https://ars.els-cdn.com/content/image/1-s2.0-S0925492717303323-gr2_lrg.jpg)

![[@Sankar2018-yp]. Fig. 3. Longitudinal changes following psychological therapies. There was a main effect of in the left precentral gyrus, which showed decreased activity following psychological therapy in major depression. The coronal (y) coordinate of each section is presented. There were additional regions which did not meet our threshold of 50 mm3 for significance. Results are *P* < 0.05 FDR corrected.](https://ars.els-cdn.com/content/image/1-s2.0-S0925492717303323-gr3_lrg.jpg)

#### Electroconvulsive Therapy (ECT)

- Last line of treatment for drug-resistant depression
- Electric current delivered to the brain causes 30-60s seizure.
- ECT usually done in a hospital's operating or recovery room  under general anesthesia.
- Once every 2 - 5 days for a total of 6 - 12 sessions.
- Remission rates of up to 50.9% [@dierckx_efficacy_2012]
- Seems to work via
    + Anticonvulsant effects (blocking Na+ channel or enhance GABA function)
    + Neurotrophic (stimulates neurogenesis) effects

#### Drugs

- Monoamine oxidase (MAO) inhibitors
    + MAO inactivates monoamines in terminal buttons
    + MAO-I’s boost monoamine levels
- Tricyclics
    + Inhibit NE, 5-HT reuptake
    + Upregulate monoamine levels, but non-selective = side effects
- Selective Serotonin Reuptake Inhibitors (SSRIs)
    + Fluoxetine (Prozac, Paxil, Zoloft)
    + Prolong duration 5-HT in synaptic cleft
    + Also increase brain steroid production
- Serotonin/Norepinephrine Reuptake Inhibitors (SNRIs)

<iframe width="420" height="315" src="https://www.youtube.com/embed/OTZvnAF7UsA" frameborder="0" allowfullscreen></iframe>

##### Drug effectiveness

- [STAR*D trial](http://www.nimh.nih.gov/funding/clinical-research/practical/stard/allmedicationlevels.shtml)
- On SSRI for 12-14 weeks. ~1/3 achieved remission; 10-15% showed symptom reduction.
- If SSRI didn't work, could switch drugs. ~25% became symptom free.
- 16% of participants dropped out due to tolerability issues
- Took 6-7 weeks to show response
- But recent reanalyses [@Pigott2023-zo] suggest "In contrast to the STAR*D-reported 67% cumulative remission rate after up to four antidepressant treatment trials, the rate was 35.0%..."

##### Who benefits from drug therapy?

- May depend on
    + Early life stress
    + Brain (amygdala) response to emotional faces [@goldstein-piekarski_human_2016]
- Low-stress + low amyg reactivity -> > responding
- High stress + high amyg reactivity -> > responding

![[@goldstein-piekarski_human_2016]](http://www.pnas.org/content/113/42/11955/F2.medium.gif)

#### Problems with monoamine hypothesis

- Too simplistic
- NE, 5-HT interact
- Drugs fast acting (min), but improvement slow (weeks)
- "No correlation between serotonin and its metabolite 5-HIAA in the cerebrospinal fluid and [11C]AZ10419369 binding measured with PET in healthy volunteers." [[@Tiger2015-dy]](http://hdl.handle.net/10616/44513)
- Monamine depletion studies...

> "*...we performed the first meta-analysis of the mood effects in ATD and APTD studies. The depletion of monoamine systems (both 5-HT and NE/DA) does not decrease mood in healthy controls. However, in healthy controls with a family history of MDD the results suggest that mood is slightly decreased...by [monoamine depletion]...*" [@Ruhe2007-qc]

::: {.callout-note}

Acute tryptophan depletion (ATD) targets 5-HT; phenylalanine/tyrosine depletion (APTD) targets DA; alpha-methyl-para-tyrosine (AMPT) targets NE/DA.

:::

>“The serotonin hypothesis of depression is still influential. We aimed to synthesise and evaluate evidence on whether depression is associated with lowered serotonin concentration or activity in a systematic umbrella review of the principal relevant areas of research. PubMed, EMBASE and PsycINFO were searched using terms appropriate to each area of research, from their inception until December 2020. Systematic reviews, meta-analyses and large data-set analyses in the following areas were identified: serotonin and serotonin metabolite, 5-HIAA, concentrations in body fluids; serotonin 5-HT1A receptor binding; serotonin transporter (SERT) levels measured by imaging or at post-mortem; tryptophan depletion studies; SERT gene associations and SERT gene-environment interactions…**The main areas of serotonin research provide no consistent evidence of there being an association between serotonin and depression, and no support for the hypothesis that depression is caused by lowered serotonin activity or concentrations**.” [@Moncrieff2022-os]

### Evaluating treatments

##### Ketamine, again

- Relieves depressive symptoms relatively quickly [@Berman2000-vg; @Zarate2006-np]
- Boosts synaptic spine formation [@Li2010-ve] and reverses effects of induced stress
- May operates via endogenous opioid system [@Jiang2024-dt]

### Putative pathway of pathology

- Depression ~ chronic stress [@mahar_stress_2014]
- Stress -> chronic HPA axis activity
- Chronic HPA activity -> neuronal atrophy in hipp & PFC
- Stress & cortisol decrease expression of brain-derived neurotrophic factor (BDNF)
- BDNF boosts neurogenesis
- SSRIs act via BDNF, as do NMDA receptor antagonists (e.g., ketamine)

![[@Duman2012-nz]](https://ars.els-cdn.com/content/image/1-s2.0-S0166223611001913-gr1.jpg)

![[@Frohlich2014-tq]](http://journals.sagepub.com/na101/home/literatum/publisher/sage/journals/content/jopa/2014/jopa_28_4/0269881113512909/20161119/images/medium/10.1177_0269881113512909-fig3.gif)

### Putting the pieces together

![[@Palazidou2012-je]](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bmb/101/1/10.1093/bmb/lds004/2/m_lds00402.jpeg?Expires=2147483647&Signature=tNJwe~EQlKXRCwAbbb5n7mHXk9PZM-2dPUr5~D~3Bttal1AEudH3CAbMs8LEbBdmQhS-ZQ4p3czOHMtev6lluG-qXIzmW3rAi6lPWIuz4iVuq7XQccT36eCCOOtuBiJjwmVkwVUzr8bxzK3qCxlSZCm6NC1tJOSIJsDpDTwRu7xR27rw28HJ9TzhA7Q47zODf0pSGPK5rG16dHhUgqX57W5Rej8ARNDJE7EvHPcIqXxodn5d9e2JRhGyQyIf4VTBu0CxAlFrv9gkihIgCnjbtMPQwpebUzvcCwYf-~cCJJWDd7H9Dmd-IA7HSMPkxFPVFTNHGC2LC86QlefZKf87WQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA)

## The disordered mind

- Multi-level, multi-method, multi-variate approaches essential to understanding mental illness
- Developmental processes across the life span
- Networks all the way down...
