---
title: "Final project"
format: html
---

## Project proposal

Please describe your plan for your final project in a concise, 1-2 page proposal.
Your proposal should describe the form of your project, the topic or topics to be covered, how the project contributes to your scholarly or training goals, and highlight and cite no more than five (5) sources you intend to draw upon.

Please submit the proposal as a Microsoft Word (.docx) formatted document.

The proposal is due on [Thursday, February 29, 2024]{.orange_due}

## Project options

## Paper options

### BBS-style critical review

Please write a critical review in the style of a [Behavioral and Brain Sciences (BBS)](https://www.cambridge.org/core/journals/behavioral-and-brain-sciences) commentary.
The target of your review could be a published article in BBS or an article published in another journal.
Examine some existing BBS papers in your areas of interest to see how authors choose to structure their commentaries.
Typically, a BBS commentary is [restricted to 1,000 words](https://www.cambridge.org/core/journals/behavioral-and-brain-sciences/information/instructions-contributors), but you have latitude to write up to 2,500 words. 

**Do's**

- Always put your last name and first name in the file name of all documents you submit. For example, `gilmore-rick-psy-511-2021-final-paper.docx` works fine.
- Submit your paper as a MS Word document or as a Google drive document that I can comment on using the track changes feature.
- Include a cover page and title. Make sure to add page numbers.
- Unpack and define all acronyms when you first mention them. Define or explain technical terms and concepts.
- Include all end-of-paper citations in a format that is convenient to you and easy to extract from your reference manager.
- Include author-date citations in the text.
- Use double-spacing.
- Run spell-check on your paper before you submit. I also suggest reading your paper out loud as a way to catch run-on sentences, awkward phrasing, and odd word choices.
