---
title: "Exercise 04 • Neurophysiology II"
---

## Goals

1. To understand what change in the resting state of neurons causes the *action potential*.
2. To understand how the action potential results in the release of neurotransmitter from the axon terminal (terminal button).

## Activity

You may work by yourself or with up to two other people for this activity.
If it is easier, you may draw separate figures for the steps below.

1. Draw a figure that shows the two principal ions that contribute to the neuron's resting potential, and where (inside or outside the neuron) they are most heavily concentrated.
2. Annotate your figure to show the direction of ion flow along each ion's concentration gradient^[1].
3. Annotate your figure to show the direction of ion movement caused by the $Na^+/K^+$ (sodium/potassium) ATPase (pump). 
4. Annotate your figure to show what spatial pattern of *electrical* charges (positive/negative voltage; inside the cell/outside the cell) would tend to keep the potassium ($K^+$) ions where they are most highly concentrated when the neuron is at rest. Explain your reasoning.
5. Annotate your figure to show what this *same* pattern of electrical charges would do to sodium ($Na^+$) ions.
6. What change(s) in the neuron could cause potassium ($K^+$) ions to move? Which direction would the ions move under these circumstances?
7. What change(s) in the neuron could cause sodium ($Na^+$) ions to move? Which direction would the ions move under these circumstances?

## Submission details

- Submit a photocopy of your outline by **Wednesday, January 24, 2023 at 5:00 pm**.
- If you found any resources that were especially useful to you, please share them.

## Simulation

<iframe src="https://phet.colorado.edu/sims/html/neuron/latest/neuron_en.html"
        width="800"
        height="600"
        allowfullscreen>
</iframe>

[1]: Remember that ions flow *down* the concentration gradient, from regions of high concentration to regions of lower concentration.

