project:
  type: website
  render:
    - "*.qmd"
    - "exercises/*.qmd"
    - "slides/*.qmd"
  output-dir: "../docs"

website:
  title: "PSYCH 511 • Spring 2024"
  comments: 
    hypothesis:
      theme: clean
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: schedule.qmd
        text: schedule
      - href: evaluation.qmd
        text: evaluation
      - href: policies.qmd
        text: policies
      - text: slides
        menu:
          - href: "slides/wk01-2024-01-11.qmd"
          - href: "slides/wk02-2024-01-18.qmd"
      - text: resources
        menu:
          - href: "resources/levels.qmd"
          - text: "---"
          - href: "resources/anatomy.qmd"
          - text: "---"
          - href: "resources/cells.qmd"
      - text: exercises
        menu: 
          - href: "exercises/ex01.qmd"
          - href: "exercises/ex02.qmd"
          - href: "exercises/ex03.qmd"
          - href: "exercises/ex04.qmd"
          - href: "exercises/ex05.qmd"
          - href: "exercises/ex06.qmd"
format:
  html:
    theme: cosmo
    css: include/css/styles.css
    toc: true
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    bibliography: [include/bib/packages.bib, include/bib/psu-repro.bib, include/bib/psy-511.bib]
    csl: include/bib/apa.csl

editor: source
    