project:
  type: website
  render:
    - "*.qmd"
    - "exercises/*.qmd"
    - "slides/*.qmd"
    - "resources/*.qmd"
  output-dir: "../docs"
  resources:
    - "include/snd/*.m4a"
    - "include/snd/*.wav"
    - "include/img/*.png"
    - "include/img/*.jpg"
    - "include/img/*.gif"
    - "include/img/*.mov"
website:
  title: "PSYCH 511.003 • Spring 2024"
  comments: 
    hypothesis:
      theme: clean
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: schedule.qmd
        text: schedule
      - href: evaluation.qmd
        text: evaluation
      - href: policies.qmd
        text: policies
      - text: slides
        menu:
          - href: "slides/wk01-2024-01-11.qmd"
            text: "Week-01 • Course introduction"
          - href: "slides/wk02-2024-01-18.qmd"
            text: "Week-02 • Neuroanatomy"
          - href: "slides/wk03-2024-01-25.qmd"
            text: "Week-03 • Cellular Neuroscience I"
      - text: resources
        menu:
          - href: "resources/levels.qmd"
          - text: "---"
          - href: "resources/anatomy.qmd"
          - text: "---"
          - href: "resources/cells.qmd"
      - text: exercises
        menu: 
          - href: "exercises/ex01.qmd"
          - href: "exercises/ex02.qmd"
          - href: "exercises/ex03.qmd"
          - href: "exercises/ex04.qmd"
          - href: "exercises/ex05.qmd"
          - href: "exercises/ex06.qmd"
          - href: "exercises/ex07-evo-devo.qmd"
          - href: "exercises/ex08-devo.qmd"
format:
  html:
    theme: cosmo
    css: include/css/styles.css
    csl: include/bib/apa.csl
    bibliography: [include/bib/psu-repro.bib, include/bib/packages.bib, include/bib/psy-511.bib]
    citations-hover: true
    footnotes-hover: true
editor: source
    