project:
  type: website
  render:
    - "*.qmd"
    - "exercises/*.qmd"
    - "slides/*.qmd"
    - "resources/*.qmd"
  output-dir: "../docs"
  resources:
    - "include/snd/*.m4a"
    - "include/snd/*.wav"
    - "include/img/*.png"
    - "include/img/*.jpg"
    - "include/img/*.gif"
    - "include/img/*.mov"
website:
  title: "PSYCH 511.003 • Spring 2024"
  comments: 
    hypothesis:
      theme: clean
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: schedule.qmd
        text: schedule
      - href: evaluation.qmd
        text: evaluation
      - href: policies.qmd
        text: policies
      - text: slides
        menu:
          - href: "slides/wk01-2024-01-11.qmd"
            text: "Week-01 • Course introduction"
          - href: "slides/wk02-2024-01-18.qmd"
            text: "Week-02 • Neuroanatomy"
          - href: "slides/wk03-2024-01-25.qmd"
            text: "Week-03 • Cellular Neuroscience I"
          - href: "slides/wk04-2024-02-01.qmd"
            text: "Week-04 • Cellular Neuroscience II"
          - href: "slides/wk05-2024-02-08.qmd"
            text: "Week-05 • Neurochemistry"
          - href: "slides/wk06-2024-02-15.qmd"
            text: "Week-06 • Methods"
          - href: "slides/wk07-2024-02-22.qmd"
            text: "Week-07 • Evolution"
          - href: "slides/wk08-2024-02-29.qmd"
            text: "Week-08 • Development"
          - href: "slides/wk09-2024-03-14.qmd"
            text: "Week-09 • Perception"
          - href: "slides/wk10-2024-03-21.qmd"
            text: "Week-10 • Action"
          - href: "slides/wk11-2024-03-28.qmd"
            text: "Week-11 • Language & Cognition"
          - href: "slides/wk12-2024-04-04.qmd"
            text: "Week-12 • Learning and Memory"
          - href: "slides/wk13-2024-04-11.qmd"
            text: "Week-13 • Schizophrenia"
          - href: "slides/wk14-2024-04-18.qmd"
            text: "Week-14 • Depression & Bipolar Disorder"
      - text: resources
        menu:
          # - href: "resources/levels.qmd"
          # - text: "---"
          # - href: "resources/anatomy.qmd"
          # - text: "---"
          # - href: "resources/cells.qmd"
          # - text: "---"
          # - href: "resources/neurochemistry.qmd"
          # - text: "---"
          # - href: "resources/methods.qmd"
          # - text: "---"
          # - href: "resources/evolution.qmd"
          # - text: "---"
          # - href: "resources/development.qmd"
          # - text: "---"
          # - href: "resources/perception.qmd"
          # - text: "---"
          # - href: "resources/action.qmd"
          # - text: "---"
          - href: "resources/cognition-language.qmd"
          - text: "---"
          - href: "resources/learning-memory.qmd"
          - text: "---"
          - href: "resources/schizophrenia.qmd"
          - text: "---"
          - href: "resources/affective-disorders.qmd"
      - text: exercises
        menu: 
          - href: "exercises/ex01.qmd"
          - href: "exercises/ex02.qmd"
          - href: "exercises/ex03.qmd"
          - href: "exercises/ex04.qmd"
          - href: "exercises/ex05.qmd"
          - href: "exercises/ex06.qmd"
          - href: "exercises/ex07-evo-devo.qmd"
          - href: "exercises/ex08-devo.qmd"
  repo-url: https://github.com/psu-psychology/psy-511-scan-fdns-2024-spring
  repo-actions: [edit, issue]
  repo-subdir: src

format:
  html:
    theme: cosmo
    css: include/css/styles.css
    csl: include/bib/apa.csl
    bibliography: [include/bib/psu-repro.bib, include/bib/packages.bib, include/bib/psy-511.bib]
    citations-hover: true
    footnotes-hover: true
    toc: true
    toc-depth: 4
    fig-align: center
    fontsize: 1.2em
editor: source
    